language: python

services:
  - docker

install:
  - docker build -t chatapp .
script:
  - docker run -d -p 5000:5000 -t chatapp
test:
  - docker run chatapp python3 test_server.py
  - docker run chatapp coverage run test_server.py
after_success:
  - pip install coveralls
  - container=`docker run -dit chatapp /bin/bash`
  - docker exec $container coverage run test_server.py
  - docker cp $container:/app/.coverage ./
  - coveralls
