language: python

services:
  - docker

install:
  - docker build -t chatapp .
script:
  - docker run -d -p 5000:5000 -t chatapp
test:
  - docker run chatapp python3 test_server.py
  - docker run chatapp coverage run test_server.py
after_success:
  - container=`docker run -dit chatapp /bin/bash`
  - docker exec $container coverage run --omit */dist-packages/* test_server.py
  - docker exec $container -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" coveralls
