language: python

services:
  - docker

before_script: 
  - tar xvf surf-2.0.tar.gz
  - cd surf-2.0 && make clean install

install:
  - docker build -t chatapp .

script:
  - docker run -d -p 5000:5000 -t chatapp
  - surf localhost:5000 &
  - surf localhost:5000 &
  - surf localhost:5000 &
  
test:
  - docker run chatapp python3 test_server.py
  - docker run chatapp coverage run test_server.py
